import type { PatchlyConfig } from '../config.js';
import { createGithubClient, createPullRequest, ensureBranch, getDefaultBranch, upsertFile } from '../services/github.js';

export async function createDocsPullRequest(params: { config: PatchlyConfig; branch: string; readme: string; contributing: string }): Promise<string> {
  const { config, branch, readme, contributing } = params;
  const gh = createGithubClient(config);
  const base = await getDefaultBranch(gh, config.repo);
  await ensureBranch(gh, config.repo, base, branch);
  await upsertFile(gh, config.repo, { path: 'README.md', content: readme, message: 'docs: add README generated by Patchly', branch });
  await upsertFile(gh, config.repo, { path: 'CONTRIBUTING.md', content: contributing, message: 'docs: add CONTRIBUTING generated by Patchly', branch });
  const title = 'docs: generate README and CONTRIBUTING with Patchly';
  const body = 'This PR was created by Patchly to add or improve README and CONTRIBUTING guidelines.';
  const url = await createPullRequest(gh, config.repo, { title, body, head: branch, base, labels: config.prLabels });
  return url;
}


